name: linux-archive-dev

services:
  vuejs:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    working_dir: /app
    volumes:
      - ../../:/app
      - node_modules:/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      WATCHPACK_POLLING: 'true'
    ports:
      - '${DOCKER_DEV_VUEJS_PORT}:5173'
    init: true

volumes:
  node_modules:
